### ISSUE TITLE
DataExplorer with null data does not accept data with empty column names

### ISSUE THREAD

**Issue by frank113** [Planeshifter/isle-editor#53]
When uploading csv data to be analyzed in the DataExplorer component (with `data={null}`), the webpage goes to a blank screen if the name of a column is blank. For example, if one were to use the R function `write.csv` with `row.names = TRUE`, the first column of the written data would have a name of `""` -- causing an error.

**Comment by Planeshifter** [comment]
Addressed in 2f238f7c6c8657f1974d07ea01e35c670f048999.
